### ISSUE TITLE
 Cannot find name 'HammerManager'.

### ISSUE THREAD

**Issue by matjanos** [CWThomson/ng2-date-time#3]
I'm getting following error

```
ERROR in [default] C:/**/DesktopMonitoring/node_modules/@angular2-material/core/gestures/MdGestureConfig.d.ts:4:39
Cannot find name 'HammerManager'.
```

**Comment by CWThomson** [comment]
From the stack trace you have given I can't see any link to this module. I did find a issue raised on the ng2-material module which seems to match your issue

[https://github.com/justindujardin/ng2-material/issues/244](url)
